# -*- coding: utf-8 -*-
"""Перевод остальных скриптов No Place Like Home.

Меняем только текст в кавычках и внутри шаблонных строк. Подстановки `${...}`
переносятся дословно: в них имена переменных, и правка сломала бы вычисление.
Ключи ролей (`rockerboy`, `solo`…) и идентификаторы компендиума не трогаем —
именно по ним модуль находит роль, а не по названию.
"""
import io
import os
import sys

sys.stdout.reconfigure(encoding="utf-8")
ROOT = r"C:\Users\Horusian\AppData\Local\FoundryVTT\Data\modules\no-place-like-home"

FILES = {
    "character-benefits.mjs": [
        # Названия ролей — только для показа: роль ищется по идентификатору.
        ('name: "Rockerboy"', 'name: "Рокербой"'),
        ('name: "Solo"', 'name: "Соло"'),
        ('name: "Netrunner"', 'name: "Нетраннер"'),
        ('name: "Tech"', 'name: "Техник"'),
        ('name: "Medtech"', 'name: "Медтех"'),
        ('name: "Media"', 'name: "Медиа"'),
        ('name: "Lawman"', 'name: "Законник"'),
        ('name: "Exec"', 'name: "Менеджер"'),
        ('name: "Fixer"', 'name: "Фиксер"'),
        ('name: "Nomad"', 'name: "Кочевник"'),

        # Исходы подработки, по шесть на роль.
        ('"Local show"', '"Выступление в районе"'),
        ('"No bookings"', '"Заказов нет"'),
        ('"Private headline gig"', '"Частный концерт хедлайнером"'),
        ('"Royalties"', '"Отчисления"'),
        ('"Support act"', '"На разогреве"'),
        ('"Appearance fee"', '"Гонорар за появление"'),
        ('"Budget protection contract"', '"Дешёвый контракт на охрану"'),
        ('"Premium protection contract"', '"Дорогой контракт на охрану"'),
        ('"High-risk contract"', '"Контракт с высоким риском"'),
        ('"Muscle for hire"', '"Наём мускулов"'),
        ('"Laying low"', '"Залёг на дно"'),
        ('"Enforcement contract"', '"Силовой контракт"'),
        ('"Small data sale"', '"Продажа мелких данных"'),
        ('"Corporate data sale"', '"Продажа корпоративных данных"'),
        ('"Unproductive week"', '"Пустая неделя"'),
        ('"Recovered data"', '"Восстановленные данные"'),
        ('"Ransomware payoff"', '"Выкуп за расшифровку"'),
        ('"Network sabotage"', '"Сетевая диверсия"'),
        ('"No commissions"', '"Заказов не было"'),
        ('"Salvage restoration"', '"Восстановление хлама"'),
        ('"Security contract"', '"Контракт на охранные системы"'),
        ('"Cybertech servicing"', '"Обслуживание кибернетики"'),
        ('"Weapon servicing"', '"Обслуживание оружия"'),
        ('"Sabotage commission"', '"Заказ на диверсию"'),
        ('"Emergency treatment"', '"Неотложная помощь"'),
        ('"Recovered implant sale"', '"Продажа снятого импланта"'),
        ('"Trauma Team assistance"', '"Работа с Trauma Team"'),
        ('"Unpaid community care"', '"Бесплатная помощь району"'),
        ('"Wealthy patient\'s procedure"', '"Операция богатому пациенту"'),
        ('"Pharmaceutical order"', '"Заказ на препараты"'),
        ('"Investigative sale"', '"Продажа расследования"'),
        ('"Popular feature"', '"Популярный материал"'),
        ('"Advertising copy"', '"Рекламный текст"'),
        ('"Controversial report"', '"Скандальный репортаж"'),
        ('"No usable leads"', '"Ни одной зацепки"'),
        ('"Major revelation"', '"Крупное разоблачение"'),
        ('"Routine arrests"', '"Обычные задержания"'),
        ('"Citizen\'s reward"', '"Награда от горожанина"'),
        ('"Salary deduction"', '"Вычет из жалованья"'),
        ('"Routine paycheck"', '"Обычная зарплата"'),
        ('"Smuggling bust bonus"', '"Премия за перехват контрабанды"'),
        ('"Gang seizure bonus"', '"Премия за изъятое у банды"'),
        ('"Project bonus"', '"Премия за проект"'),
        ('"Bonus withheld"', '"Премию задержали"'),
        ('"Office leverage"', '"Рычаг в конторе"'),
        ('"Major project reward"', '"Награда за крупный проект"'),
        ('"Reallocated rival funding"', '"Перехваченное финансирование соперника"'),
        ('"Information brokerage"', '"Торговля сведениями"'),
        ('"Booking commission"', '"Комиссия за организацию"'),
        ('"Sourcing commission"', '"Комиссия за поиск товара"'),
        ('"Failed deal"', '"Сделка сорвалась"'),
        ('"Job placement fee"', '"Плата за подбор работы"'),
        ('"Rare goods brokerage"', '"Посредничество в редком товаре"'),
        ('"Cargo run"', '"Рейс с грузом"'),
        ('"Convoy security"', '"Охрана колонны"'),
        ('"Small smuggling run"', '"Мелкая контрабанда"'),
        ('"Major smuggling run"', '"Крупная контрабанда"'),
        ('"Passenger delivery"', '"Доставка пассажира"'),
        ('"No transport work"', '"Работы по перевозкам нет"'),

        # Отказы и сообщения.
        ("Hustle needs a supported Role, rank 1–10 and a d6 result.",
         "Для подработки нужна поддерживаемая роль, ранг от 1 до 10 и результат d6."),
        ("Character resource values are invalid.",
         "Значения ресурсов персонажа испорчены."),
        ("Healing days must be a positive whole number.",
         "Число дней лечения — целое положительное."),
        ("Cannot calculate healing from this character's BODY.",
         "Не удалось посчитать лечение по ТЕЛУ этого персонажа."),
        ("Choose a character you currently own.",
         "Выберите персонажа, которым владеете."),
        ("You no longer have access to this HQ record.",
         "У вас больше нет доступа к этой записи штаба."),
        ("HQ access is lost. Its benefit actions are unavailable.",
         "Доступ к штабу потерян, его блага недоступны."),
        ("You do not own any Cyberpunk RED characters.",
         "У вас нет ни одного персонажа Cyberpunk RED."),
        ('"Natural healing"', '"Естественное лечение"'),
        ('"Monthly Humanity recovery"', '"Восстановление человечности за месяц"'),
        ('"Weekly Hustle"', '"Недельная подработка"'),
        ('"Heal character"', '"Лечить персонажа"'),
        ('"Roll & restore Humanity"', '"Бросить и восстановить человечность"'),
        ('"Choose Role"', '"Выбор роли"'),
        ("This character needs a Role item with a rank from 1 to 10 to Hustle.",
         "Для подработки персонажу нужна роль с рангом от 1 до 10."),
        ('"Roll Hustle"', '"Бросить подработку"'),
        ("A benefit action is already running for this character.",
         "Для этого персонажа уже выполняется действие блага."),
        ("Character updated, but the chat receipt could not be posted. Do not repeat the action.",
         "Персонаж изменён, но запись в чат не ушла. Повторять действие не нужно."),
        ("Monthly Humanity requires at least one Morale Boost upgrade.",
         "Месячная человечность требует хотя бы одной ступени «Подъёма духа»."),
        ("HQ monthly Humanity recovery — rolled amount (before maximum cap)",
         "Восстановление человечности за месяц — выпавшее значение, до ограничения максимумом"),
        ("HQ benefits changed during the roll; no Humanity was applied.",
         "Блага штаба изменились во время броска — человечность не начислена."),
        ("Choose one of this character's Role items.",
         "Выберите одну из ролей этого персонажа."),
        ("Choose one of the two Hustle results.",
         "Выберите один из двух исходов подработки."),
        ("HQ benefits changed during the Hustle; no money was applied.",
         "Блага штаба изменились во время подработки — деньги не начислены."),
        ("Cannot read this character's Eurobucks ledger.",
         "Не удалось прочитать счёт евробаксов этого персонажа."),
        ('"both paid"', '"оба засчитаны"'),
        ('"Unknown benefit action."', '"Неизвестное действие блага."'),
        ('"Choose your Hustle result"', '"Выберите исход подработки"'),
        ('"Credit selected income"', '"Засчитать выбранный доход"'),
        ("<label>Character<select name=", "<label>Персонаж<select name="),
        ("${actor.name} — Hustle Role", "${actor.name} — роль для подработки"),
        ("<label>Character's Role<select name=", "<label>Роль персонажа<select name="),
        ("<label>Hustle table<select name=", "<label>Таблица подработки<select name="),
        ('<option value="">Choose a table…</option>', '<option value="">Выберите таблицу…</option>'),
        ("<p>The rank comes from your Role item. Check the table for renamed or custom Roles.</p>",
         "<p>Ранг берётся из роли персонажа. Для переименованных и своих ролей выберите таблицу вручную.</p>"),
        ("Healed ${result.gained} HP over ${days} day(s): (BODY ${body} + HQ ${bonus}) × ${days}. HP ${before} → ${result.value} (maximum ${hp.max}).",
         "Вылечено ${result.gained} ОЗ за ${days} дн.: (ТЕЛО ${body} + штаб ${bonus}) × ${days}. ОЗ ${before} → ${result.value} (максимум ${hp.max})."),
        ("Monthly Humanity: restored ${result.gained}; ${before} → ${result.value} (maximum ${max}). EMP ${Math.floor(result.value / 10)}.",
         "Человечность за месяц: восстановлено ${result.gained}; ${before} → ${result.value} (максимум ${max}). ЭМП ${Math.floor(result.value / 10)}."),
        ("HQ Hustle — ${HUSTLES[table].name}, Rank ${rank}, roll ${i + 1} (not yet credited)",
         "Подработка штаба — ${HUSTLES[table].name}, ранг ${rank}, бросок ${i + 1} (ещё не засчитан)"),
        ("HQ Hustle: ${HUSTLES[table].name} rank ${rank}, d6 ",
         "Подработка штаба: ${HUSTLES[table].name}, ранг ${rank}, d6 "),
        ("Increased wealth by ${amount} to ${wealth.value + amount}.",
         "Деньги выросли на ${amount}, стало ${wealth.value + amount}."),
        ("Hustle credited ${amount}eb for seven days. ",
         "Подработка принесла ${amount} eb за семь дней. "),
        ("<p>Morale Boost lets you keep either result:</p>",
         "<p>«Подъём духа» позволяет оставить любой из двух исходов:</p>"),
    ],
    "crew-ip.mjs": [
        ('"Improvement Points"', '"очков улучшения"'),
        ("Select at least one crew character.", "Выберите хотя бы одного бойца команды."),
        ("The selected crew has changed. Reopen the popup and select current crew characters.",
         "Состав команды изменился. Закройте окно, откройте заново и выберите нынешних бойцов."),
        ("This awards new money; no funds are taken from the shared stash.",
         "Это начисляет новые деньги — с общего склада ничего не списывается."),
        ("The HQ IP balance is managed separately.",
         "Запас ОУ штаба ведётся отдельно."),
        ("Enter a positive whole number of ${unit} per character.",
         "Введите целое положительное число: ${unit} на каждого персонажа."),
        ('Enter a reason for the ${money ? "money" : "IP"} award.',
         'Укажите причину начисления: ${money ? "деньги" : "ОУ"}.'),
        ("does not have a valid ${money ? \"Eurobucks\" : \"Improvement Points\"} ledger.",
         "— негодный счёт: ${money ? \"евробаксы\" : \"очки улучшения\"}."),
        ("+${amount} ${unit}; balance ${ledger.value + amount} ${unit}",
         "+${amount} ${unit}; стало ${ledger.value + amount} ${unit}"),
        ('Only the GM can award crew ${money ? "money" : "IP"}.',
         'Начислять команде ${money ? "деньги" : "ОУ"} может только мастер.'),
        ('${money ? "Money" : "IP"} award completed for: ',
         'Начисление (${money ? "деньги" : "ОУ"}) прошло для: '),
        ('Failed: ${failed.join(", ")}. Check those characters before retrying; do not re-award successful recipients.',
         'Не прошло: ${failed.join(", ")}. Проверьте этих персонажей перед повтором; тем, кому начислилось, повторно не начисляйте.'),
        ("Awarded ${amount} ${unit} each to ${awarded.length} crew member(s): ",
         "Начислено по ${amount} ${unit} — бойцов: ${awarded.length}: "),
        ("Only the GM can award crew ${label}.", "Начислять команде ${label} может только мастер."),
        ("Link at least one Character actor in the six crew slots first. Vehicles and NPC mooks cannot receive ${label} here.",
         "Сперва поставьте хотя бы одного персонажа в шесть мест команды. Транспорт и шестёрки ${label} здесь не получают."),
        ("Award crew ${label}", "Начислить команде: ${label}"),
        ("<p>Select the crew members who receive this award.</p>",
         "<p>Отметьте бойцов, которым идёт начисление.</p>"),
        ('data-select-crew="all">Select all<', 'data-select-crew="all">Выбрать всех<'),
        ('data-select-crew="none">Clear<', 'data-select-crew="none">Снять<'),
        ("<label>${unit} per selected character<", "<label>${unit} каждому отмеченному<"),
        ("<label>Reason<textarea", "<label>Причина<textarea"),
        ('placeholder="${money ? "Mission payment, bonus…" : "Mission completed, roleplay award…"}"',
         'placeholder="${money ? "Оплата за дело, премия…" : "Дело закрыто, награда за отыгрыш…"}"'),
        ("<p>The full amount goes to each selected character. ",
         "<p>Каждому отмеченному идёт полная сумма. "),
        ("Award ${label}", "Начислить: ${label}"),
        ("${count} / ${actors.length} selected", "отмечено ${count} из ${actors.length}"),
    ],
    "hq-assets.mjs": [
        ("Choose one of the six crew slots.", "Выберите одно из шести мест команды."),
        ("That character is already in the crew.", "Этот персонаж уже в команде."),
        ('"Missing sheet"', '"Лист пропал"'),
        ('"Empty slot"', '"Пусто"'),
        ('"Restricted sheet"', '"Лист закрыт"'),
        ("That sheet no longer exists. Ask the GM to replace its link.",
         "Этого листа больше нет. Попросите мастера привязать другой."),
        ("You do not have permission to open that sheet.",
         "У вас нет прав открыть этот лист."),
        ("The GM manages crew and garage links.",
         "Привязками команды и гаража занимается мастер."),
        ("Drop a sheet from this world, not a compendium.",
         "Перетащите лист из этого мира, а не из компендиума."),
        ("Crew slots accept character or NPC Actor sheets.",
         "В места команды кладут листы персонажей или НИП."),
        ("Drop a vehicle Item or an Actor used as a vehicle sheet.",
         "Перетащите транспорт — предметом или листом актёра."),
        ("Ask the GM to create the shared stash.", "Попросите мастера завести общий склад."),
        ("The system could not create the stash.", "Система не смогла создать склад."),
        ('"Invalid Eurobucks ledger."', '"Негодный счёт евробаксов."'),
        ("Not enough Eurobucks for this transfer.", "Не хватает евробаксов на эту передачу."),
        ("You cannot access this HQ.", "У вас нет доступа к этому штабу."),
        ("Enter a positive whole amount of Eurobucks.",
         "Введите целое положительное число евробаксов."),
        ("You need Owner permission on the shared stash.",
         "Нужны права владельца на общий склад."),
        ("A stash transfer is already in progress. Please wait.",
         "Передача со склада уже идёт, подождите."),
        ("Transfer failed; the deducted money was refunded.",
         "Передача не удалась, списанные деньги возвращены."),
        ("You need an owned character to transfer money.",
         "Чтобы передавать деньги, нужен свой персонаж."),
        ('"Deposit Eurobucks"', '"Положить евробаксы"'),
        ('"Withdraw Eurobucks"', '"Снять евробаксы"'),
        ("${hq.name} — Shared Stash", "${hq.name} — общий склад"),
        ("balance ${value}eb", "остаток ${value} eb"),
        ("Reversed failed transfer: ${reason}", "Неудачная передача отменена: ${reason}"),
        ("Transfer failed and refund failed. Ask the GM to reconcile ${amount}eb on ${source.name} before retrying.",
         "Передача не удалась, и возврат тоже. Попросите мастера свести ${amount} eb у «${source.name}» перед повтором."),
        ('${direction === "deposit" ? "Deposited" : "Withdrew"} ${amount}eb for ${actor.name}.',
         '${direction === "deposit" ? "Положено" : "Снято"} ${amount} eb для «${actor.name}».'),
        ("<label>Eurobucks<input name=", "<label>Евробаксы<input name="),
    ],
    "module.mjs": [
        ("Enter a valid non-negative whole number; original beds must be at least 1.",
         "Введите целое неотрицательное число; исходных мест должно быть хотя бы одно."),
        ("Original beds cannot be lower than the purchased extra beds.",
         "Исходных мест не может быть меньше, чем уже куплено дополнительных."),
        ("Custom improvement no longer exists.", "Своего улучшения больше нет."),
        ("Custom improvement was removed while editing.",
         "Своё улучшение удалили, пока его правили."),
        ('"Delete custom improvement"', '"Удалить своё улучшение"'),
        ('"Crew purchase"', '"Покупка команды"'),
        ("The purchase cost changed. Please review the new price and try again.",
         "Цена покупки изменилась. Посмотрите новую и попробуйте снова."),
        ("Enter a positive whole HQ IP award.",
         "Введите целое положительное число ОУ штаба."),
        ('"Lose improvement"', '"Потеря улучшения"'),
        ('"Team Member departure"', '"Уход соратника"'),
        ("<p>Resolve the Workstation obligation by having the Improved Team Member leave?</p>",
         "<p>Закрыть обязательство по рабочему месту, отпустив улучшенного соратника?</p>"),
        ("Improved Team Member departed; Workstation obligation cleared",
         "Улучшенный соратник ушёл; обязательство по рабочему месту закрыто"),
        ('"HQ destroyed"', '"Штаб разрушен"'),
        ("<p>Lose every improvement and upgrade without refund? Unspent HQ IP remains available for the crew's next HQ.</p>",
         "<p>Потерять все улучшения и ступени без возврата? Нетронутые ОУ штаба останутся команде на следующий штаб.</p>"),
        ("HQ destroyed; improvements lost without refund",
         "Штаб разрушен; улучшения потеряны без возврата"),
        ("Ask your GM to create a Headquarters.", "Попросите мастера создать штаб-квартиру."),
        ('"New Headquarters"', '"Новая штаб-квартира"'),
        ('"Headquarters - No Place Like Home"', '"Штаб-квартира — No Place Like Home"'),
        ("${entry ? 'Edited' : 'Added'} custom improvement: ${data.name}",
         "${entry ? 'Изменено' : 'Добавлено'} своё улучшение: ${data.name}"),
        ("and its acquired upgrades without an HQ IP refund?</p>",
         "и все купленные ступени без возврата ОУ?</p>"),
        ("<p>Delete ${escapeHTML(entry.name)} ", "<p>Удалить «${escapeHTML(entry.name)}» "),
        ("Deleted custom improvement: ${entry.name}; no refund",
         "Удалено своё улучшение: ${entry.name}; без возврата"),
        ("<p>Spend ${cost} HQ IP on ${escapeHTML(name)}? Confirm that the crew agrees.</p>",
         "<p>Потратить ${cost} ОУ штаба на «${escapeHTML(name)}»? Убедитесь, что команда согласна.</p>"),
        ("Purchased ${name} (-${cost} HQ IP)", "Куплено: ${name} (−${cost} ОУ штаба)"),
        ("Awarded ${amount} HQ IP; clear any practiced skill bonuses after a Group IP award",
         "Начислено ${amount} ОУ штаба; после групповых ОУ снимите прибавки от занятий"),
        ("<p>Remove ${escapeHTML(name)} and all its upgrades without an HQ IP refund?</p>",
         "<p>Убрать «${escapeHTML(name)}» со всеми ступенями без возврата ОУ?</p>"),
        ("Lost ${name}; no refund", "Потеряно: ${name}; без возврата"),
    ],
    "custom-improvements.mjs": [
        ("<p>Define a custom improvement for this HQ. Acquire it and its upgrades using the normal purchase buttons.</p>",
         "<p>Опишите своё улучшение для этого штаба. Покупается оно и его ступени обычными кнопками.</p>"),
        ("<label>Name<input name=", "<label>Название<input name="),
        ("<label>Base benefit<textarea name=", "<label>Основное благо<textarea name="),
        ("<label>Upgrade benefits — one upgrade per line, in purchase order<textarea name=",
         "<label>Блага ступеней — по одной в строке, в порядке покупки<textarea name="),
        ("<p>Leave upgrades blank for a base-only improvement. Effects are applied manually. Editing an acquired benefit changes its description immediately.</p>",
         "<p>Оставьте ступени пустыми, если улучшение без них. Действие применяется вручную. Правка уже купленного блага меняет его описание сразу.</p>"),
    ],
}

total = 0
for name, pairs in FILES.items():
    path = os.path.join(ROOT, "scripts", name)
    text = io.open(path, encoding="utf-8").read()
    holes = text.count("${")
    applied, missing = 0, []
    for old, new in pairs:
        if old in text:
            text = text.replace(old, new)
            applied += 1
        else:
            missing.append(old[:60])
    if text.count("${") != holes:
        sys.exit(f"{name}: число подстановок изменилось")
    io.open(path, "w", encoding="utf-8", newline="\n").write(text)
    total += applied
    print(f"  {name}: переведено {applied} из {len(pairs)}")
    for m in missing:
        print("      не найдено:", m)

print(f"\nвсего строк переведено: {total}")
